### ISSUE TITLE
Master Plan for full IoT system integration

### ISSUE THREAD

**Issue by rngadam** [coderbunker/demoZuerich#2]
For each of the checklist item below, create an issue, link it here next to the checklist item and have it assigned to a single team member. 

Refer to the issue in your commits (```issue #```)

* [ ]  source code + README.md for every subsystem (each in its own subfolder) [milestone 1](https://github.com/coderbunker/demoZuerich/milestone/1)
  * [x] MobileDataAcquisition (React-Native) [issue 4](https://github.com/coderbunker/demoZuerich/issues/4)
  * [x] Sensor (Arduino microcontroller) [issue 5](https://github.com/coderbunker/demoZuerich/issues/5)
  * [x] MessageQueue (MQTT/RabbitMQ) [issue 6](https://github.com/coderbunker/demoZuerich/issues/6)
  * [x] Database (PostgreSQL) [issue 7](https://github.com/coderbunker/demoZuerich/issues/7)
  * [x] API server (Postgraphql) [issue 8](https://github.com/coderbunker/demoZuerich/issues/8)
  * [ ] WebDashboard (React) [issue 9](https://github.com/coderbunker/demoZuerich/issues/9)
  * [x] DevOps (Nginx, Linux, VM, instance setup) [issue 10](https://github.com/coderbunker/demoZuerich/issues/10)
  * [x] EmbeddedComputer (RPi) [issue 11](https://github.com/coderbunker/demoZuerich/issues/11)
* [ ] a recorded series videocap presentation on Youtube for every subsystem "neighbors" [milestone 2](https://github.com/coderbunker/demoZuerich/milestone/2)
  * [ ] one video per "neighbours" pair [issue 13](https://github.com/coderbunker/demoZuerich/issues/13)
  * [ ] have a concrete example of data run through the system [issue 14](https://github.com/coderbunker/demoZuerich/issues/14)
  * [ ] assemble as a playlist [issue 15](https://github.com/coderbunker/demoZuerich/issues/15)
* [ ]  main demoZuerich README.md [milestone 3](https://github.com/coderbunker/demoZuerich/milestone/3)
  * [x] an overview of what the system is trying to achieve [issue 17](https://github.com/coderbunker/demoZuerich/issues/17)
  * [x] a series of link in order to the necessary documentation to setup a whole system quickly after checking out this source code. [issue 18](https://github.com/coderbunker/demoZuerich/issues/18)
  * [x] link to a running demo system[issue 19](https://github.com/coderbunker/demoZuerich/issues/19)
  * [ ] screenshots of frontends [issue 20](https://github.com/coderbunker/demoZuerich/issues/20)
  * [ ] developers guide [issue 21](https://github.com/coderbunker/demoZuerich/issues/21)

## testing

* [ ] test that a non-team member can setup the application and use the system
* [ ] test that the server can be rebooted and come up with all services available
